### ISSUE TITLE
No keyboard navigation?

### ISSUE THREAD

**Issue by mdmcginn** [googlecodelabs/tools#11]
The only way I could scroll down the page in the ES6 and First Progressive Web App labs was by dragging the scrollbar down. 

What happened: Page Down and down arrow both moved me to the next screen. 
What should have happened: Down arrow should move me further down the screen, not to the next screen.

**Comment by x1ddos** [comment]
I think this is the same as #46.

**Comment by x1ddos** [comment]
I meant https://github.com/googlecodelabs/codelab-components/issues/46
