### ISSUE TITLE
We should center images

### ISSUE THREAD

**Issue by ToddKerpelman** [googlecodelabs/tools#114]
We need to find a way to center images. In many cases, it would make the generated codelab look much better. In fact, I would argue that it should be the default.

**Comment by nicolasgarnier** [comment]
I'm not against making it the default. Is there any reasons we don't do it? :)

**Comment by nicolasgarnier** [comment]
Looks like this may work with a CSS-only fix with this rule:

```css
img:FIRST-CHILD {
    display: flex;
    margin: auto;
}
```

That ensures inline images (like small icons in text) are note screwed up. But I have to test on more browsers to make sure.

**Comment by nicolasgarnier** [comment]
Never min, this will likely require changes to the compiler to identify images that are on their own lines. OR will be an opt-in (via just centering the image in the doc :)
