### ISSUE TITLE
claat should store oauth tokens

### ISSUE THREAD

**Issue by petele** [googlecodelabs/tools#12]
Running claat requires it to auth every, single, time, it's run. It would be awesome if it could store my oauth tokens, so I don't need to auth every time I run it.

We use it to deploy code labs to d.g.c/web, which means it's usually run 4 or 5 times a week by the same person.

**Comment by x1ddos** [comment]
It does store authentication.
It must be your local setup.

How do you run it?

**Comment by x1ddos** [comment]
Also, do you see any warnings/errors?
Can you post the output of running a "claat export ..." or "claat update
..."

**Comment by x1ddos** [comment]
A potential fix was submitted in commit https://github.com/googlecodelabs/tools/commit/f771be8dcbcbf02c00b0e1a1d4ee5513f03ce550.
New binaries are available at the usual locations.

**Comment by petele** [comment]
That fixed it, thanks!
