### ISSUE TITLE
claat tool should auto-generate author tag for web fundamentals

### ISSUE THREAD

**Issue by marcacohen** [googlecodelabs/tools#13]
Consider supporting an optional metadata field for including authorship attribution in the generated codelab.

@petele - Did you want this to generate a WF specific tag in the generated markdown? Or include an author field in the codelab.json file, which could be parsed by the web fundamentals build tooling?

**Comment by petele** [comment]
I want to be able to specify the author in the table at the head of the Google doc (similar to summary, url, category, env, status), and have that included in the `codelab.json` file when the codelab is exported or updated with the CLAAT tool.

**Comment by x1ddos** [comment]
What format should the new field be? An example would be nice. For instance:

    "author": "dude <user@example.com>"

or 

    "author": "an arbitrary text, I don't care what it is"

**Comment by x1ddos** [comment]
I mean, it doesn't really matter for the claat parser as long as it's a string of text, but we should agree on a common format so that we can explain it to the writers. What this fields means and what it does, so that they can use it appropriately.

**Comment by petele** [comment]
Def the latter, arbitrary text is ideal for us.

**Comment by x1ddos** [comment]
If any of you guys fancy a code review to close this: https://github.com/googlecodelabs/tools/pull/14

**Comment by x1ddos** [comment]
@petele update your local claat tool copy and you'll see the author field on the next codelab update/export.
