### ISSUE TITLE
Code blocks contained within <ol>s are not indented to match the <ol>

### ISSUE THREAD

**Issue by shawnbuso** [googlecodelabs/tools#135]
If you have an &lt;ol&gt; that contains code blocks, the &lt;pre&gt; tags for the code blocks aren't indented to match the &lt;ol&gt;. 

![image](https://user-images.githubusercontent.com/1238504/50613202-cb53b280-0eaa-11e9-82df-343100feff3b.png)

It looks like the reason is that the &lt;ol&gt;s are split and the &lt;pre&gt;s are rendered between them, like so:

```
<ol type="1" start="1"><li>Step 1</li></ol>
<pre>Code for step 1</pre>
<ol type="1" start="2"><li>Step 2</li></ol>
<pre>Code for step 2</pre>
```

If possible, instances like the example above should just be one &lt;ol&gt; containing the &lt;pre&gt;s.

**Comment by shawnbuso** [comment]
Diving into this a bit further, I'm not sure if we can fix this in the exporter. I took a look at the source doc for this issue and it looks like it's doing the same thing - it treats each step as its own ordered list, and the code blocks as separate from that list, but indented. If you try to include the code blocks in the list, you get numbers prefixing your code, which is unwanted. A solution to this would likely involve changing the way the codelab source doc is written, and potentially paring that with a change in the export tool or the rendering code.

**Comment by M4FFS** [comment]
![image](https://user-images.githubusercontent.com/40577281/89203538-a191ce80-d5ac-11ea-8bd1-5a361b8178b1.png)
