### ISSUE TITLE
Update handleDrawerClick_ to use a real URL parser to get the hash value

### ISSUE THREAD

**Issue by shawnbuso** [googlecodelabs/tools#139]
Currently handleDrawerClick_ calculates the step that was clicked by just removing the first character of the href, and assuming everything else is the step. This breaks if those links turn into full URLs to the step. For example, in the left nav:
```
<a href="#1"></a>
```
correctly navigates you to step 1, but:
```
<a href="codelabs.com/my-codelab#1"></a>
```
tries to navigate to step "odelabs.com/my-codelab#1". We should instead use a URL parser to parse the href param, then get the hash value from said URL parser.

**Comment by nicolasgarnier** [comment]
fixed in #158
