### ISSUE TITLE
Text paragraphs are being misinterpreted as images, incorrectly being centered

### ISSUE THREAD

**Issue by orendain** [googlecodelabs/tools#212]
Claat is tagging text paragraphs as image containers, resulting in text paragraphs having their non-image content centered and looking funky.

The logic behind tagging a paragraph as an imageNode is here:
https://github.com/googlecodelabs/tools/blob/master/claat/render/html.go#L255

Edit: Can be reproduced by running claat on the sample gdoc.

**Comment by nicolasgarnier** [comment]
This was normally fixed in https://github.com/googlecodelabs/tools/commit/dfd48e54e0d17a132c6a5a41bac038323d6a9f3d

Are you using a release or are you building from master? I think we have not done a release yet since.

**Comment by orendain** [comment]
Looks like I was linking a build slightly older than when this was fixed - sorry for the mixup - thanks for clearing that up!
