### ISSUE TITLE
Scrolling on Drawer is breaks page if there is large number of steps.

### ISSUE THREAD

**Issue by ablenesi** [googlecodelabs/tools#226]
For code labs with more than 12 - 13 steps scrolling is broken:
![Screenshot 2019-04-22 at 16 41 33](https://user-images.githubusercontent.com/10282350/56503379-ea3f8880-651d-11e9-9c8f-da23fe0e3b76.png)

To reproduce the issue simply view the code lab preview for this code lab doc: 
https://docs.google.com/document/d/1meGkYFAbyuhOd4KpP_e2WTUi6hrmOe0y-oq9ky5dwmw/edit?usp=sharing

The generated URL by the chrome plugin:
https://codelabs-preview.appspot.com/?o=driveui&file_id=1meGkYFAbyuhOd4KpP_e2WTUi6hrmOe0y-oq9ky5dwmw

**Comment by nicolasgarnier** [comment]
As per the PR, this was already fixed in the codebase but the previewer has not yet been updated with the latest version of the codelab elements.
