### ISSUE TITLE
How to create a codelab?

### ISSUE THREAD

**Issue by vietstone** [googlecodelabs/tools#27]
Sorry, I don't know my question is eligible or not. But currently I want to create a codelab-style tutorial on my own. Is there a guide to do it? Thank you.

**Comment by cassierecher** [comment]
The [README](https://github.com/googlecodelabs/tools/blob/master/README.md) explains how to do this.

**Comment by vietstone** [comment]
Thanks @cassierecher , I will check it soon

**Comment by mariopce** [comment]
check this https://medium.com/@mariopce/tutorial-how-to-make-tutorials-using-google-code-labs-gangdam-style-d62b35476816
