### ISSUE TITLE
Access Token Issue

### ISSUE THREAD

**Issue by labnol** [googlecodelabs/tools#274]
I am getting the 401 Invalid Credentials error when running the claat binary.

I checked the access token with the https://www.googleapis.com/oauth2/v3/tokeninfo?access_token= API and it is valid.

I am not a Go programmer but it looks like the issue is related to this line in auth.go

https://github.com/googlecodelabs/tools/blob/32c99de00853fd262de428128d28f140e16b369d/claat/cmd/auth.go#L72

When a new access token is supplied (say after an hour), the claat binary is still using credentials generated from the old access token and hence is is unable to fetch the document using the Drive API.

I think the clients[providerGoogle] value should be set to nil if the access token in the current request is different from the access token in the previous request.

**Comment by Marcial1234** [comment]
Hmm that's odd. That line hasn't changed in 3+ years (map lookup with static variables), so it sounds more like an issue with the authenticator to me.
 
We have a flag for your use case:
https://github.com/googlecodelabs/tools/blob/bc176f1638ec227e63652f9e25e2cf7380a29c1f/claat/main.go#L43
which overrides where the saved auth key is being used:
https://github.com/googlecodelabs/tools/blob/32c99de00853fd262de428128d28f140e16b369d/claat/cmd/auth.go#L92
Try with that for now, let us know how it goes! 😃

**Comment by labnol** [comment]
Thank you for looking into this.

I am actually passing the authToken directly and the issue happens only when the token is changed. I am using Docker. If I rebuild the binary, it works again probably because the existing credentials created by the old access token are reset.

	exitCode := cmd.CmdExport(cmd.CmdExportOptions{
		AuthToken: token,
		Srcs:      []string{""https://docs.google.com/document/d/docID"},
		Expenv:    "web",
		Output:    folder,
		Tmplout:   "html"
	})

**Comment by labnol** [comment]
With my limited knowlege of Go, even if the authToken is supplied, aren't we calling tokenSource only if the clients[providerGoogle] is not nil?

Could that be a reason why the request may be failing when the access token has changed because the old credentials are still getting used by the driveClient.

```
// driveClient returns an HTTP client which knows how to perform authenticated
// requests to Google Drive API.
func driveClient(authToken string) (*http.Client, error) {
	clientsMu.Lock()
	defer clientsMu.Unlock()
	if hc, ok := clients[providerGoogle]; ok {
		return hc, nil
	}
	ts, err := tokenSource(providerGoogle, authToken)
	if err != nil {
		return nil, err
	}
	t := &oauth2.Transport{
		Source: ts,
		Base:   http.DefaultTransport,
	}
	hc := &http.Client{Transport: t}
	clients[providerGoogle] = hc
	return hc, nil
}
```

**Comment by labnol** [comment]
I've been able to resolve this issue by making [one change](https://github.com/labnol/tools/commit/3d43905ed848d21cb5fb5b6e25888d9fd4446336) in the auth.go file.

![Access Token Fix](https://user-images.githubusercontent.com/1344071/58618839-316d2600-82e1-11e9-9274-aeee58df7e6e.png)

Basically, the Clients map value should change if the authToken has changed else it will serve the old credentials and the Drive API won't be able to fetch the document.

**Comment by Marcial1234** [comment]
Great to know you were able to fix it.

Feel free to send a PR with the code change that fixed this issue.

**Comment by labnol** [comment]
#275 

PR Sent. Thanks!

**Comment by labnol** [comment]
Merged https://github.com/googlecodelabs/tools/pull/275#event-2403380119
