### ISSUE TITLE
How can I deploy this tools on aws server??

### ISSUE THREAD

**Issue by clearcodecn** [googlecodelabs/tools#289]
My mean is to write markdown and compile to codelab styles.
and I want to deploy it on my local or custom server.
Is there any example?

**Comment by cassierecher** [comment]
I'm not sure there are direct examples, but I think the tool output can be handled by [a wide variety of servers](http://go/gh/googlecodelabs/tools/pull/153).

**Comment by clearcodecn** [comment]
thanks.
