### ISSUE TITLE
Source format instructions not found

### ISSUE THREAD

**Issue by balazsbanyai** [googlecodelabs/tools#3]
The help says that the source formats currently supported are:
- Google Doc (Codelab Format, go/codelab-guide)
- Markdown

However, i was unable to find any instructions on how to format the input document.

**Comment by crhym3** [comment]
It's a good point. @marcacohen we should probably finish the review of the public codelabs guide and publish it.

**Comment by balazsbanyai** [comment]
@crhym3 any update on this? It would be extremely helpful to be able to create my own codelabs for tutorials, etc.

**Comment by marcacohen** [comment]
Hi @balazsbanyai. Yes, sorry for the delay on this. We'll prioritize publishing this doc and make it available this week (most likely by end of day Tuesday).

**Comment by balazsbanyai** [comment]
That's great news! I'm looking forward to it!

**Comment by marcacohen** [comment]
@balazsbanyai I've updated the readme for this repo. See if it addresses your need and let me know. Thanks!
