### ISSUE TITLE
formatting oddness with multiple bolds in one line

### ISSUE THREAD

**Issue by djschny** [googlecodelabs/tools#32]
I have a Google Doc with a bulleted list and each bullet has bolder, then monospaced font, then plain text, then bolding and then plain text. However the formatting comes out odd in regards to the formatting on Qwiklab. The Google Doc and the Chrome Plugin appear to render properly though.

See the following screenshots to help.

**Google Doc**
<img width="526" alt="screen shot 2017-08-07 at 2 52 39 pm" src="https://user-images.githubusercontent.com/129643/29047325-1b876ab8-7b80-11e7-9a39-44ba8fac6fbb.png">

**Chrome Plugin**
<img width="497" alt="screen shot 2017-08-07 at 2 53 15 pm" src="https://user-images.githubusercontent.com/129643/29047336-2aeb5b22-7b80-11e7-9c66-d46dc68ee223.png">

**Qwiklabs**
<img width="666" alt="screen shot 2017-08-07 at 2 53 41 pm" src="https://user-images.githubusercontent.com/129643/29047350-38af3f62-7b80-11e7-8aa1-153cb5ffcd66.png">

**Comment by x1ddos** [comment]
@djschny sorry, I have no idea what Qwiklabs are doing. I know they made an internal fork of this. I would recommend filing internal issue against qwiklabs.
