### ISSUE TITLE
-f option broke as of an hour ago

### ISSUE THREAD

**Issue by behoyh** [googlecodelabs/tools#334]
I was working on getting some markdown into Codelabs for a demo I was going to do at work tomorrow, but for some reason it looks like the last commit broke the option to build Codelabs from markdown. Please help?

**Comment by behoyh** [comment]
Closing, as a simple login fixes the issue. (Google login is now mandatory?)

**Comment by cassierecher** [comment]
I might have accidentally made it so login is mandatory. That wasn't my intention, sorry about that. I'll see about fixing it when I have time.
