### ISSUE TITLE
Column headers not showing up in HTML output

### ISSUE THREAD

**Issue by Pflanzgurke** [googlecodelabs/tools#399]
Hi,

it seems that the column headers are not rendered when creating tables from markdown or directly as HTML inside the markdown. I used an example which was reported on the mailing list as working. See example codelab Markdown below.

Thanks a lot for the Codelabs Tools!

```
summary: Table Test
id: tbtst
categories: Tests
tags: Test
status: Draft 
authors: Tobi Test
analytics account: 0

# Heading 1
## Heading 2
Duration: 2:00

The headers will be gone after rendering

<table>
<tr>
<th>Header 1</th> <th>Header 2 </th>
</tr>
<tr>
<td> Test</td> <td>Test 2</td>
</tr>
<tr>
<td>A</td><td>B</td>
</tr>
</table>

The below will miss the column headings in the generated HTML output

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

**Comment by KeyboardNerd** [comment]
Thanks for reporting the bug, Pflanzgurke!
We found the problem to be reproducible:
![Image](https://raw.githubusercontent.com/KeyboardNerd/keyboardnerd.github.io/master/Screen%20Shot%202020-03-25%20at%201.28.39%20PM.png)

**Comment by M4FFS** [comment]
https://github.com/googlecodelabs/tools/pull/432
