### ISSUE TITLE
Download button not rendered from Markdown

### ISSUE THREAD

**Issue by Pflanzgurke** [googlecodelabs/tools#402]
Hi,

I believe the download button is not being rendered, when starting a link with the word `download`. It should be possible according to the documentation. Below is a Markdown file to reproduce the problem.

```
summary: Download Test
id: dltst
categories: Tests
tags: Test
status: Draft 
authors: Tobi Test
analytics account: 0

# Heading 1
## Heading 2
Duration: 2:00

According to [this](https://github.com/googlecodelabs/tools/tree/master/claat/parser/md#download-buttons) if a link starts with the word `Download`, a button should be rendered, which does not work for me.

[Download](https://www.wireshark.org/#download)
```

Thank you for the Codelab tools! In times of Corona, I started to use them A LOT and they are really helpful for my use case!

**Comment by jetzlstorfer** [comment]
I'm having the same issue.

**Comment by MoonWolf125** [comment]
Also had this issue. Compared it against an inspected Google codelab and found that there was no paper-button inside the hyperlink.

**Comment by MoonWolf125** [comment]
Did some digging. This is related to #55 which states that button parsing was removed in #33 

It's within this section of the parser that the leading "download " is handled:
https://github.com/googlecodelabs/tools/blob/d557ecbfc54e92ee85c3f1e2f5e05f453702374d/claat/parser/md/parse.go#L692

**Comment by M4FFS** [comment]
Button links can be done in the following way in markdown: 

https://github.com/googlecodelabs/tools/pull/379#issuecomment-613709303

The documentation will be updated to reflect this
