### ISSUE TITLE
SEO friendly?

### ISSUE THREAD

**Issue by rrjanbiah** [googlecodelabs/tools#41]
At @RestyaPlatform we're very much interested to try codelabs (thanks for open sourcing it!) for documentation section of our Restyaboard (open source Trello alternative). We understand that it is static HTML. But, as it also uses Polymer, will there be any impact on SEO? TIA

**Comment by x1ddos** [comment]
It's SEO friendly as any other web app based on Custom Elements.
For instance, see these links: https://www.google.ch/search?q=custom+elements+seo. 

Also, try searching on google.com for a codelab you'll see on codelabs.developers.google.com.

**Comment by rrjanbiah** [comment]
@x1ddos Thanks for your reply.
