### ISSUE TITLE
Got empty result after export

### ISSUE THREAD

**Issue by shawnhsiao** [googlecodelabs/tools#43]
I try install claat and export my google doc.
the result page only get title of doc, content are empty.
any suggestion?
Mac: 10.12.6
Browser : Chrome

<img width="1062" alt="2018-03-28 3 30 50" src="https://user-images.githubusercontent.com/14923482/38015240-c07ae16a-329d-11e8-9465-dcc3cf1f409b.png">

also I tried use preview url(https://codelabs-preview.appspot.com/?file_id=18dnMdUJQaGKY1Tit_-fO1YOpOpAbA4hh0YDXQlCEjvA)
It only show : No steps found for environment "web"

Do I need any auth to run that?

**Comment by shawnhsiao** [comment]
now I copy a doc from https://docs.google.com/document/d/1rpHleSSeY-MJZ8JvncvYA8CFqlnlcrW8-a4uEaqizPY.
and now it works.
still not knowing what setting need to done in Doc

**Comment by x1ddos** [comment]
@shawnhsiao the doc you've tried to preview is the codelabs formatting guide. It is not a codelab.
The second doc you reference is indeed a codelab template. It's a good starting point. Use it.
