### ISSUE TITLE
Click-to-copy button in command-line snippets

### ISSUE THREAD

**Issue by tswast** [googlecodelabs/tools#52]
It would be useful if command-line snippets had a button to copy-to-clipboard. Docs on cloud.google.com have this ability, and it would be convenient for codelabs, too.

![image](https://user-images.githubusercontent.com/247555/41556611-26a78de8-72f0-11e8-9a93-3744aaff764b.png)

**Comment by x1ddos** [comment]
Thanks for report. This is indeed a feature requested before more than once.
This would be done on the UI part, mostly in javascript. Already created https://github.com/googlecodelabs/codelab-elements/issues/14 for this.

**Comment by vorburger** [comment]
see #133
