### ISSUE TITLE
Shouldn't link url start with https?

### ISSUE THREAD

**Issue by ohjeongwook** [googlecodelabs/tools#532]
"https:" might be missing from line 24, 25.

https://github.com/googlecodelabs/tools/blob/c1d945f0ebcfcf56c18d213eb72d9445fb57077f/claat/render/template.html#L24

https://github.com/googlecodelabs/tools/blob/c1d945f0ebcfcf56c18d213eb72d9445fb57077f/claat/render/template.html#L25

**Comment by shawnbuso** [comment]
This one is working as intended - if you just start the link with "//" it will copy the protocol of the parent page.

**Comment by ohjeongwook** [comment]
Yes, I figured it worked like that. But, if we can give https:// prefix to the URLs, we have benefit of loading the HTML files locally. With current URL scheme loading HTML files locally takes long time due to timeout situation. I think claat is not intended to be used through server, but it can still be beneficial and also, we better enforce https traffic.
