### ISSUE TITLE
github.com/googlecodelabs/tools/claat/cmd [setup failed]

### ISSUE THREAD

**Issue by janelle1106** [googlecodelabs/tools#540]
Followed the Dev workflow mentioned [here](https://github.com/googlecodelabs/tools/tree/master/claat). But I got this error when I tested it.

![Screen Shot 2021-01-26 at 8 50 38 AM](https://user-images.githubusercontent.com/24517178/105784494-e58deb00-5fb3-11eb-9cea-0e03875a5503.png)

Is there any step config I possibly skipped?

**Comment by contributorpw** [comment]
* Why are you in `./cmd`? What are you doing there?
* Did you setup your `$GOPATH`?
* Beware you need to clone the repo into `$GOPATH/src/github.com/`
* You need to `call go get ./...` from `$GOPATH/src/github.com/googlecodelabs/tools/claat`
* Make sure that `make` may some make for your OS.

There are very simple dependencies. You don't need anything special for this deployment.

**Comment by janelle1106** [comment]
Thanks Alex, I've missed on step upon the setting up. It's all good now. Thank you!
