### ISSUE TITLE
RE: Google CodeLabs and Using it for Github.io Repo Typed Websites...

### ISSUE THREAD

**Issue by silver2row** [googlecodelabs/tools#549]
Hello,

Is it possible to use this technology for setting up websites w/ github.io?

Seth

P.S. I say yes b/c of the landing page for googlecodelabs/tools on github but I am not sure exactly how to approach this idea. I have not seen anyone else do it thus far.

**Comment by contributorpw** [comment]
The tools generate an independent static site. You can deploy it to any https server even github.io.

**Comment by silver2row** [comment]
Hello...okay. Thank you. 

Seth
