### ISSUE TITLE
/build/index.html has error

### ISSUE THREAD

**Issue by Nthily** [googlecodelabs/tools#563]
why when I use `gulp serve --codelabs-dir=codelabs`, it shows up fine in http://localhost:8000/, but when I click on index.html in the /build folder but it doesn't display properly? (edited) 

![xwro_736pwdosr__k_h85t6](https://user-images.githubusercontent.com/31311826/116751627-9917d880-aa04-11eb-9ba1-a73926c05c2b.png)
![image](https://user-images.githubusercontent.com/31311826/116751636-9a490580-aa04-11eb-9c14-90ec39e09814.png)

**Comment by Nthily** [comment]
How do I deploy to github pages?

**Comment by Nthily** [comment]
When I push the whole site folder to the github repository and change the build folder to docs as github pages, the page is not rendered, I don't know if it's a gulp problem

**Comment by Nthily** [comment]
![$I90LS_0TZ 4 5G POTC37M](https://user-images.githubusercontent.com/31311826/116779742-68718680-aa78-11eb-9901-ece9ede9becf.png)

**Comment by karthik-jorrigal** [comment]
Hi, Even I am facing the same issue. have you managed to resolve this?

**Comment by Nthily** [comment]
@karthik-jorrigal Look at this project https://github.com/compose-museum/codelabs

**Comment by Nthily** [comment]
> @karthik-jorrigal Look at this project https://github.com/compose-museum/codelabs

look at this Path

**Comment by karthik-jorrigal** [comment]
@Nthily thank you for a quick reply, I appreciate it.
I copied your repo and replaced my files, as follows..
![image](https://user-images.githubusercontent.com/82152269/119190810-74f76680-ba9b-11eb-8127-d8ffd4b11d8c.png)


but No LUCK !! - I still see the index page without the styling
my repo: https://github.com/karthik-jorrigal/codelabs
page: https://karthik-jorrigal.github.io/codelabs/
![image](https://user-images.githubusercontent.com/82152269/119191092-d4557680-ba9b-11eb-9057-06d7b48bc0cf.png)

not sure where I am going wrong.

**Comment by Nthily** [comment]
> @Nthily thank you for a quick reply, I appreciate it.
> I copied your repo and replaced my files, as follows..
> ![image](https://user-images.githubusercontent.com/82152269/119190810-74f76680-ba9b-11eb-8127-d8ffd4b11d8c.png)
> 
> but No LUCK !! - I still see the index page without the styling
> my repo: https://github.com/karthik-jorrigal/codelabs
> page: https://karthik-jorrigal.github.io/codelabs/
> ![image](https://user-images.githubusercontent.com/82152269/119191092-d4557680-ba9b-11eb-9057-06d7b48bc0cf.png)
> 
> not sure where I am going wrong.

try to create new Branch

**Comment by Nthily** [comment]
This error also happens when I use master branch

**Comment by karthik-jorrigal** [comment]
> 
> 
> @karthik-jorrigal Look at this project https://github.co

> 
> 
> This error also happens when I use master branch

Oh, i see, I will try moving the code to a different branch and try.

**Comment by Nthily** [comment]
you can try to create gh-pages branch, and go to setting set

**Comment by Nthily** [comment]
![image](https://user-images.githubusercontent.com/31311826/119191446-f1c81780-ba7e-11eb-9cb9-0b78e35e049e.png)

**Comment by karthik-jorrigal** [comment]
I don't have a custom domain and I hope that will be an issue.

Am now trying it out with gh-pages branch.

**Comment by Nthily** [comment]
> I don't have a custom domain and I hope that will be an issue.
> 
> Am now trying it out with gh-pages branch.

yes, an error will also occur if a custom domain name is not applied

**Comment by karthik-jorrigal** [comment]
> 
> 
> > I don't have a custom domain and I hope that will be an issue.
> > Am now trying it out with gh-pages branch.
> 
> yes, an error will also occur if a custom domain name is not applied

Looks like that is the case, I tried with gh-pages - No Luck. 
I don't have a custom domain at the moment, will try out Netlify or something.

![image](https://user-images.githubusercontent.com/82152269/119192438-c99be100-ba9d-11eb-9207-ead6fb648e3e.png)

**Comment by Nthily** [comment]
BTW, ![image](https://user-images.githubusercontent.com/31311826/119192512-939c3400-ba80-11eb-91da-1e74b95b0476.png)
![image](https://user-images.githubusercontent.com/31311826/119192535-9d259c00-ba80-11eb-9b94-b60b1a885782.png)

You should move the stuff under build/ to the root directory

**Comment by Nthily** [comment]
The purpose of this is to identify index.html, and as for the rendering of css, it seems to be related to the path

**Comment by Nthily** [comment]
The codelabs in the root directory do not need to be changed

**Comment by karthik-jorrigal** [comment]
> 
> 
> BTW, ![image](https://user-images.githubusercontent.com/31311826/119192512-939c3400-ba80-11eb-91da-1e74b95b0476.png)
> ![image](https://user-images.githubusercontent.com/31311826/119192535-9d259c00-ba80-11eb-9b94-b60b1a885782.png)
> 
> You should move the stuff under build/ to the root directory

I actually copied build folder & pushed the files to github directly (to /root directory)
then pushed app/ directory (which is under site directory) to github

**Comment by karthik-jorrigal** [comment]
> 
> 
> The codelabs in the root directory do not need to be changed



> 
> 
> > BTW, ![image](https://user-images.githubusercontent.com/31311826/119192512-939c3400-ba80-11eb-91da-1e74b95b0476.png)
> > ![image](https://user-images.githubusercontent.com/31311826/119192535-9d259c00-ba80-11eb-9b94-b60b1a885782.png)
> > You should move the stuff under build/ to the root directory
> 
> I actually copied build folder & pushed the files to github directly (to /root directory)
> then pushed app/ directory (which is under site directory) to github

Also pushed codelabs folder (under site/ directory) & apps folder (under tools/ directory)

**Comment by karthik-jorrigal** [comment]
I tired out deploying this to Netlify - Something went wrong
![image](https://user-images.githubusercontent.com/82152269/119193958-01a42380-baa0-11eb-8c56-2253ca68bbda.png)

**Comment by karthik-jorrigal** [comment]
Thanks @Nthily . Appreciate your support.

**Comment by Nthily** [comment]
Can I run it successfully now?

**Comment by karthik-jorrigal** [comment]
> 
> 
> Can I run it successfully now?

I couldn't run it successfully :(
https://karthik-jorrigal.github.io/codelabs/ - it is still the same without any styles.

**Comment by karthik-jorrigal** [comment]
error when running on netlify
![image](https://user-images.githubusercontent.com/82152269/119219143-a014a100-bb01-11eb-9b04-3f50d8ab6a3c.png)


seems something wrong with my code

**Comment by Nthily** [comment]
http://test.compose.net.cn/

**Comment by Nthily** [comment]
bro, it looks like domain Name Issues

**Comment by Nthily** [comment]
I tested it for you with my domain and it works fine

![)E%ABJ_Z)4STKG@0WCX8{OP](https://user-images.githubusercontent.com/31311826/119219501-3aff8200-bae6-11eb-83b2-594f712f45fb.png)

And I think your localhost should also show up fine, and the path to deploy to github.io is xxxx.github.io/projectName, not the root directory, so I think that should be the problem

**Comment by Nthily** [comment]
http://test.compose.net.cn/codelabs/applib-dev-guide/index.html?index=..%2F..index#0

**Comment by Nthily** [comment]
by the way, you should use `Unix LF` to save file, Otherwise, your code will display error

**Comment by Nthily** [comment]
![image](https://user-images.githubusercontent.com/31311826/119219706-2b346d80-bae7-11eb-8f88-34b6b641eb91.png)

**Comment by Nthily** [comment]
To verify that it's a domain path issue, I also tested it for you and it works perfectly when you use your own github.io

https://nthily.github.io/

**Comment by karthik-jorrigal** [comment]
> 
> 
> To verify that it's a domain path issue, I also tested it for you and it works perfectly when you use your own github.io
> 
> https://nthily.github.io/

Hi, Can  I copy the method you followed? I am a project manager by profession, not an experienced coder.

**Comment by karthik-jorrigal** [comment]
> 
> 
> > To verify that it's a domain path issue, I also tested it for you and it works perfectly when you use your own github.io
> > https://nthily.github.io/
> 
> Hi, Can I copy the method you followed? I am a project manager by profession, not an experienced coder.
Where did you push this?

**Comment by karthik-jorrigal** [comment]
I tried copying your codelab, but i could not get pass this page without the styles
https://karthik-jorrigal.github.io/compose-museum/

I think it is the way I am creating the page is wrong..
I am pushing the code to a repo > branch, and then creating a page /root.. -> step seems to be wrong

**Comment by karthik-jorrigal** [comment]
And I think your localhost should also show up fine, and the path to deploy to github.io is xxxx.github.io/projectName, not the root directory, so I think that should be the problem

```how do I set it up in the way you suggested?```
-

**Comment by karthik-jorrigal** [comment]
> 
> 
> I tested it for you with my domain and it works fine
> 
> ![)E%ABJ_Z)4STKG@0WCX8{OP](https://user-images.githubusercontent.com/31311826/119219501-3aff8200-bae6-11eb-83b2-594f712f45fb.png)
> 
> And I think your localhost should also show up fine, and the path to deploy to github.io is xxxx.github.io/projectName, not the root directory, so I think that should be the problem

Yes, My localhost is showing up fine. It's the issue with the github page.

**Comment by Nthily** [comment]
Create a respority called your github name .github.io, and push file to there

**Comment by Nthily** [comment]
https://pages.github.com/

**Comment by Nthily** [comment]
In my case, it's nthily.github.io, then push the file there, set the github pages, and you're done

**Comment by karthik-jorrigal** [comment]
> 
> 
> In my case, it's nthily.github.io, then push the file there, set the github pages, and you're done

Alright! I will try this out and will let you know if I am successful.

**Comment by karthik-jorrigal** [comment]
@Nthily - it worked!
https://karthik-jorrigal.github.io/
thank you, you are awesome!

**Comment by karthik-jorrigal** [comment]
but when I click on any codelab - it throws 404 error
![image](https://user-images.githubusercontent.com/82152269/119226726-3fe52580-bb28-11eb-9050-68738fb8a0c3.png)


I think I can figure this out. But if you have the answer ready, then pls let me know. I remember facing this issue before.. I maintain a separate repository and added codelabs folder there...

**Comment by Nthily** [comment]
![image](https://user-images.githubusercontent.com/31311826/119226841-6a74b580-bb0b-11eb-946e-0a2b046b0ce5.png)

？

**Comment by karthik-jorrigal** [comment]
yea, it worked after clearing browser cache.

**Comment by karthik-jorrigal** [comment]
> 
> 
> by the way, you should use `Unix LF` to save file, Otherwise, your code will display error

Yes, I fixed this as well.
``` $txt = [io.file]::ReadAllText('.\cdlbs\how-to-write-a-codelab.md') -replace "`r`n","`n" >> [io.file]::WriteAllText('.\cdlbs\how-to-write-a-codelab3.md', $txt) ```
