### ISSUE TITLE
Latest update breaking

### ISSUE THREAD

**Issue by sparsh-ai** [googlecodelabs/tools#581]
sudo add-apt-repository ppa:longsleep/golang-backports -y
sudo apt update
sudo apt install golang-go
sudo env GOPATH=/root/go
sudo go get github.com/googlecodelabs/tools/claat
sudo cp /root/go/bin/claat /usr/bin/

go get claat -> 2nd last line - breaking

ERROR:
go get: gopkg.in/russross/blackfriday.v2@none updating to
	gopkg.in/russross/blackfriday.v2@v2.1.0: parsing go.mod:
	module declares its path as: github.com/russross/blackfriday/v2
	        but was required as: gopkg.in/russross/blackfriday.v2

**Comment by flochlaysebastien** [comment]
Hi,
I have the same problem. I tried to start from the [Docker Official Images](https://hub.docker.com/layers/golang/library/golang/1.16.5/images/sha256-c70ccb70c93f2f3b365a2d9a65520d77d08d4ac338309914af54ee5abc219565?context=explore) to avoid any side effects, but I am getting the same problem with `gopkg.in/russross/blackfriday.v2`.

```bash
$ docker run -it golang:1.16.5 /bin/bash
root@e082072b608b:/go# go get github.com/googlecodelabs/tools/claat
go: downloading github.com/googlecodelabs/tools v1.2.1
go: downloading github.com/googlecodelabs/tools/claat v0.0.0-20210610195942-369125588564
go: downloading github.com/googlecodelabs/tools v2.2.4+incompatible
go get: github.com/googlecodelabs/tools/claat@none updating to
	github.com/googlecodelabs/tools/claat@v0.0.0-20210610195942-369125588564 requires
	gopkg.in/russross/blackfriday.v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by sparsh-ai** [comment]
It is now resolved for me. 
I removed the first line - sudo add-apt-repository ppa:longsleep/golang-backports -y

**Comment by flochlaysebastien** [comment]
There is no longer a problem if I switch to an older version like Golang1.15.

> Resolved : Don't use golang:1.16, switch to golang:1.15

**Comment by cassierecher** [comment]
I think this might be resolved with 1.16 now -- could someone verify?

**Comment by cassierecher** [comment]
No wait, I reproduced it being broken again.

**Comment by cassierecher** [comment]
I've removed blackfriday as a dependency; this should be fixed now.
