### ISSUE TITLE
missing lots of codelabs for android

### ISSUE THREAD

**Issue by shalva97** [googlecodelabs/tools#589]
lots of codelabs are missing from the list on `https://codelabs.developers.google.com/?cat=android`. What happened?
I was completing one, which was about Dagger, but ctrl + f doesnot find it anymore...

**Comment by cassierecher** [comment]
Sorry about that! We were having an issue with our index. I think it's fixed now though, are you seeing what you expect?

**Comment by shalva97** [comment]
yes its working, thanks
