### ISSUE TITLE
Go get deprecated with Go 1.17: Readme.md should be updated.

### ISSUE THREAD

**Issue by astridhanghoej** [googlecodelabs/tools#645]
Starting in Go 1.17, installing executables with go get is deprecated (see:https://golang.org/doc/go-get-install-deprecation).

Following guide from https://github.com/googlecodelabs/tools/tree/main/claat#install will yield the following error message:

go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

Readme.md should be updated.

**Comment by TamimiGitHub** [comment]
Any recommendation on how to approach this? The way i've been working around this is cloning the repo and adding an alias to claat (or updating the PATH) to the executable

**Comment by cassierecher** [comment]
The new instructions specified in #693 seem to work.
