### ISSUE TITLE
Create a claat build command

### ISSUE THREAD

**Issue by Gillespie59** [googlecodelabs/tools#78]
Hi, 

First I want to thank you for your tool. I am started using it for my own codelabs. 

If I understand well, the basic workflow is : 

```
claat export ...
claat serve 
```

The last command is important because all bower dependencies will be downloaded. 

Do we have another command for downloading these dependencies, without launching an HTTP server. For example a `claat build` ?

Second question, I am looking for a docker image in order to launch claat commands without Go on my system. Do you have this image ?

Thanks again.

**Comment by x1ddos** [comment]
> Second question, I am looking for a docker image in order to launch claat commands without Go on my system. Do you have this image ?

You don't necessary need Go, neither Docker. See first paragraph in https://github.com/googlecodelabs/tools/blob/master/claat/README.md#install
