### ISSUE TITLE
Codelab elements not loading

### ISSUE THREAD

**Issue by Snickdx** [googlecodelabs/tools#801]
On the built codelab site I keep geetting 404/3 on the code lab dependencies  [example](https://weblabs.web.app/1601l1/)

![image](https://user-images.githubusercontent.com/5845054/202188095-06b9fdb7-dfd9-4f9e-b25f-0dc108a9f35f.png)

I've tried updating claat but  the error persists

**Comment by bwnyasse** [comment]
Guys, 
it seems that the buckets are not public anymore. any change on the Cloud storage ? 
https://storage.googleapis.com/codelab-elements/codelab-elements.css

**Comment by coisme** [comment]
I hope the original URL recovered.

**Comment by PengBAI** [comment]
any news on the 403 or I'm missing somethings

**Comment by Comeani** [comment]
There's a discussion on this here: https://groups.google.com/g/codelab-authors/c/WwSdRF4bjBE

**Comment by khammami** [comment]
@Snickdx use [the latest claat release](https://github.com/googlecodelabs/tools/releases/tag/v2.2.5) to re-export your labs or you can do it manually using an IDE by changing any occurence of `/codelab-elements/` to `/claat-public/` in the index of your previously exported labs

**Comment by Snickdx** [comment]
Awesome! It works now thanks!
