### ISSUE TITLE
Getting a 404 File not found error when previewing codelabs

### ISSUE THREAD

**Issue by filiph** [googlecodelabs/tools#803]
Hi,

Until earlier today, I was able to preview my draft codelab via https://codelabs-preview.appspot.com/?file_id=1i2lh1X9M9Uow6ERypdTF94sHNOPqNtoa-eA5Q08s6Ek.

But now, all I see is:

```
https://docs.google.com/document/d/1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k/edit?usp=sharing: fetch https://www.googleapis.com/drive/v3/files/1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k?fields=id%2CmimeType%2CmodifiedTime&supportsTeamDrives=true: 404 Not Found; {
  "error": {
    "code": 404,
    "message": "File not found: 1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k.",
    "errors": [
      {
        "message": "File not found: 1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k.",
        "domain": "global",
        "reason": "notFound",
        "location": "fileId",
        "locationType": "parameter"
      }
    ]
  }
}
```

Force-reloading doesn't help. 

I get the same error for [another codelab preview](https://codelabs-preview.appspot.com/?file_id=1rstsDJ4C_VBzSfX6_-ezCtmCCxiXDlkci6f9sjinHGM) that I didn't author (but have access to).

On the other hand, [this yet-another codelab preview](https://codelabs-preview.appspot.com/?file_id=1NJq1PfV9mB2avhoM2l12DSQ8p2x6s_epXcLwCcZwpcg#0) works for me just fine.

And, confusingly, when @domesticmouse accesses [the preview link](https://codelabs-preview.appspot.com/?file_id=1i2lh1X9M9Uow6ERypdTF94sHNOPqNtoa-eA5Q08s6Ek) of my own codelab draft, the one that fails with a 404 error for me, he can see the preview just fine. ¯\_(ツ)_/¯ 

I should say that I'm using an external (`@gmail`) account. I created the gdoc with that account, and I'm also signed into that account when accessing `codelabs-preview.appspot.com`. 

To re-iterate: this worked for me just fine earlier today. From some point today onwards, it ceased to work and now I only see the 404 error.

**Comment by domesticmouse** [comment]
I can reproduce this error with my brett@domesticmouse.com account:

```console
https://docs.google.com/document/d/1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k/edit?usp=sharing: fetch https://www.googleapis.com/drive/v3/files/1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k?fields=id%2CmimeType%2CmodifiedTime&supportsTeamDrives=true: 404 Not Found; {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: 1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k.",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: 1SP6-Ky12u1vE03QjPie8OtdQXZtgx5NaPxGyXPRey8k."
 }
}
```

**Comment by rosera** [comment]
Tested this on my personal account. It looks like an invalid/expired authentication token.
Removing the cookie and then re-authenticating allowed me to access the doc using my personal account. To fix it, I did the following:

- [  ] Click on the SSL padlock
- [  ] Click Cookies option
- [  ] Remove the associated cookies.
- [  ] Re-authenticate to the service

Should now have access to the Codelab document.

**Comment by domesticmouse** [comment]
Even after deleting cookies following the above process it still failed to auth. I'm happy to share the document with Googlers for testing purposes.

**Comment by rosera** [comment]
Feel free to send across for further testing.

**Comment by domesticmouse** [comment]
Turns out, the issue was that the document contained imports that these accounts did not have access to. I've raised an issue internally to ask for more useful debug information on the error page.
