### ISSUE TITLE
Display Video

### ISSUE THREAD

**Issue by josephkandi** [googlecodelabs/tools#90]
Is it possible to display video using `<video src="">` tag? I have tried and i do not get any output or a Youtube video. I noticed in one of the commits there's a mention on Youtube videos here ,https://github.com/googlecodelabs/tools/commit/9e85b7dcd8add8bce4b91625b2ad8fb1239d440d?

I use MkDocs for my other documentation sites and am able to show video use HTML in markdown, is this possible with `claat`?

**Comment by marcacohen** [comment]
Adding a related issue. As a work around for embedded video I suggested adding a hyperlink to a still image of a video but was told that doesn't work either. I'll take a look at both of these.

**Comment by josephkandi** [comment]
Shouldnt this be working https://github.com/googlecodelabs/tools/commit/9e85b7dcd8add8bce4b91625b2ad8fb1239d440d?. Or is this in a different release?

**Comment by josephkandi** [comment]
Any updates on this. I really need to add a Youtube video inside my docs, how can i do this? Anyone

**Comment by nicolasgarnier** [comment]
Youtube videos are now supported but without start time. The way to embed them is described here: https://github.com/googlecodelabs/tools/blob/master/FORMAT-GUIDE.md (search for "Youtube"). Let me know if you have any questions.

**Comment by josephkandi** [comment]
I tried this `![https://www.yoututbe.com/watch?v=R21EU8SKUM0](https://www.youtube.com/watch?v=RgKAFK5djSk)` but it still doesnt work. Is that only supported for using Google Docs not Markdown?

**Comment by nicolasgarnier** [comment]
It's possible. Let me check the code.

**Comment by nicolasgarnier** [comment]
So it looks like this is supported in the MD parser: https://github.com/googlecodelabs/tools/blob/542dc91d14a79331791bbc6a3d16932226d921c3/claat/parser/md/parse.go#L641

**Comment by nicolasgarnier** [comment]
It should be a URL to an image though such as: ![https://www.yoututbe.com/watch?v=R21EU8SKUM0](image URL here).

Are you generating HTML as an output?

**Comment by nicolasgarnier** [comment]
I'm asking because if you are using Markdown as your output then this is not yet supported: https://github.com/googlecodelabs/tools/blob/879b5d21e27d54350c3b983d24e9584f4afc2971/claat/render/md.go#L117-L118
