### ISSUE TITLE
Neither `Codelab Formatting Guide` nor `example doc` links are publicly accessible

### ISSUE THREAD

**Issue by solex** [googlecodelabs/tools#91]
Both links mentioned in the snippet below point to the private Google Docs. Since the `README` is public I would expect the Formatting Guide to be public too.

--

https://github.com/googlecodelabs/tools/blob/master/README.md#L50

1. Create a doc following the syntax conventions described in the [Codelab Formatting Guide](https://g.co/codelabs/guide). Here’s an [example doc](https://docs.google.com/document/d/1rpHleSSeY-MJZ8JvncvYA8CFqlnlcrW8-a4uEaqizPY/edit). Feel free to copy that doc as a starter template. Once you have your own source doc, note its DocId, which is the long string near the end of the URL (right after docs.google.com/document/d/).

**Comment by solex** [comment]
Apparently the `README` mentions that you need to join a Google Group in order to access the documents. 

Still doesn't seem right that the critical part of the documentation for the open source tool requires special access.

**Comment by marcacohen** [comment]
The example doc is now publicly readable and the formatting guide is now part of the repo so no longer any need to join the author group, unless you want to.
