### ISSUE TITLE
Can't run site on newer mac 

### ISSUE THREAD

**Issue by ahna92** [googlecodelabs/tools#914]
**Issue** 
tried to follow the setup for [site](https://github.com/googlecodelabs/tools/tree/main/site) 

but faced issues like can't run `npm i` due to : 
* python3 is not supported 
* node-saas is not maintained 

any plans to update it ?

**Comment by davidaparicio** [comment]
Hello! Have you tried with this version [nodeJSv19](https://github.com/davidaparicio/tools/tree/dev/nodeJSv19) for this [PR](https://github.com/googlecodelabs/tools/pull/831) ? :-)

**Comment by ahna92** [comment]
@davidaparicio thank you !! it works, closed [here](https://github.com/googlecodelabs/tools/pull/831)
