### ISSUE TITLE
Tool Tip displayed everywhere on all pages

### ISSUE THREAD

**Issue by nicolasgarnier** [googlecodelabs/tools#97]
_From @jaysonfrazer on August 13, 2018 6:1_

Hi guys, in the Firebase codelab for friendly chat, there is a mouse tooltip that fires on every part of the page, so every time you move the mouse, the tool tip pops up no matter where you are on the page, it's really annoying and not the right use of a tool tip IMHO. Is this a mistake?
 The page I'm on is ...

https://codelabs.developers.google.com/codelabs/firebase-web/#7

_Copied from original issue: firebase/friendlychat-web#300_

**Comment by nicolasgarnier** [comment]
Looks like this happens on many (probably all) codelabs, there is a tooltip displayed everywhere on all page like this: 
![image](https://user-images.githubusercontent.com/3766663/46257141-4cb73580-c4b5-11e8-9078-becc77dc2f9a.png)

**Comment by ajh3** [comment]
I have the same problem on all the Android codelabs I've done so far. Small but extremely annoying issue that strongly impacts the usability of the codelabs - really needs to be fixed.

**Comment by nicolasgarnier** [comment]
Fixed with the new custom elements version.
